### PR TITLE
API Spec updates to readability, broken link fix, and updates to editors section to reflect code owners file

### PR DESCRIPTION
**Pull request by Ybittan**
API Spec updates to readability, broken link fix, and updates to editors section to reflect code owners file. This PR also replaced 'prvd' with 'bsln' in example did's, to keep the standard completely agnostic.

### CODE REVIEW

**Review by Therecanbeonlyone1969 — APPROVED** [review]
LGTM

**Review by Therecanbeonlyone1969 — CHANGES_REQUESTED** [review]
use an existing did method ...  I think proved actually has its did method registered. Otherwise use something like did:elem

**Comment by Ybittan** [comment]
> use an existing did method ... I think proved actually has its did method registered. Otherwise use something like did:elem

Replaced 'bsln' with 'elem'

**Review by Therecanbeonlyone1969 — APPROVED** [review]
LGTM now

**Review by chaals — APPROVED** [review]
LGTM

**Pull request merged**
