### PR TITLE
Several updates to readability and formatting consistency 

### PR DESCRIPTION
**Pull request by Ybittan**
R303 update to follow bullet list consistency

### CODE REVIEW

**Review by Therecanbeonlyone1969 — APPROVED** [review]
LGTM

**Review by Therecanbeonlyone1969 — APPROVED** [review]
LGTM

**Review by Therecanbeonlyone1969 — APPROVED** [review]
LGTM

**Review by Therecanbeonlyone1969 — APPROVED** [review]
LGTM

**Review by chaals — APPROVED** [review]
One comment, but YMMV and I think it's OK either way

**Pull request merged**
