### PR TITLE
Initial commit of section: Data Inputs (Oracles)

### PR DESCRIPTION
**Pull request by gmondok**
Added Section 8, first draft attempting to cover synchronizing data input and removing variance/counterparty risk such that the proof inputs are trustworthy and deterministic.

### CODE REVIEW

**Comment by gmondok** [comment]
Comments from Aug 5th review:
-D for SHOULD, O for MAY, C if it's conditional
-Replace blockchain with CCSM
-Change Input data to Input data to a BPI workstep
-R320, include that this is for "outside a BPI user's system of record"
-R321, For BPI input data from outside the system of record, there MUST be multiple validating parties
Andreas' note: "if input data to a BPI Workstep originates from outside of the system of records of the BPI User participating in the BPI Workstep, the input data MUST be validated by the BPI User participating in the BPI Workstep or their authorized BPI User delegates. Note, the threshold condition for validation is dependent on the business rules of the BPI Workstep"
-Define reporting entity
-3 scenarios 1) data comes from a source a BPI user authoritatively controls 2) outside data source, users agree upon it being authoritative and deterministic 3) Authoritative source, not deterministic (this is the oracle case)

**Review by Consianimis — CHANGES_REQUESTED** [review]
@Therecanbeonlyone1969 - I reviewed and gave it a go:

8. BPI External Data Inputs
This section of the document focuses on the requirements and considerations related to the input of external data into a BPI workstep. Specifically, it addresses:
-	 internal authoritative data - data sourced from a single authoritative source, internal to one of the BPI participants to a BPI workstep(i.e. internal systems of record) 
-	 external authoritative data - data sourced from external authoritative sources (i.e. government record) and
-	external non-authoritative, non-deterministic data sourced from external non-authoritative, non-deterministic sources (i.e. IoT sensor data, time, etc).

8.1 Internal Authoritative Data for BPIs
Internal authoritative data means that there exists only one authoritative version of the input data in some system of record of a BPI participant, making it the only choice for input into a BPI workstep. Authoritative in this context, means that BPI participants involved in a BPI workstep have agreed that the source is the accurate and reliable truth for that particular data point.
[O10] Internal authoritative input data to a BPI workstep MAY come from a single source.
[CR36]>[O10] If the internal authoritative input data to a BPI workstep is single-sourced, that source MUST be authoritative.

8.2 External Authoritative Data for BPIs
External authoritative data means that the input data to a BPI workstep is held in some authoritative 3rd party database, such as government records. Unlike internal authoritative data where there is only one source, external authoritative data input to a BPI workstep may have multiple sources.
[R319] BPI participants MUST agree upon the source and type of the external authoritative data used as input to a BPI workstep.

8.3 External Non-authoritative, Non-deterministic for BPIs (Oracles)
External non-authoritative, non-deterministic data means that there does not exist an authoritative, deterministic source for the data used as input to a BPI workstep. In that case, a mechanism known as an oracle is needed to account for potential discrepancies. The entities themselves which report external non-authoritative, non-deterministic into a BPI worksteps may also be referred to as oracles. 
8.3.1 Data Trustworthiness
External non-authoritative, non-deterministic data for BPIs resides outside of an authoritative source and is subject to manipulation risks. As such, steps should be taken to remove counterparty manipulation and error risk through mechanisms such as redundancy in the data reporting and error checking, either cross-party, by a neutral party or an honesty incentivized party. 
[D34] External non authoritative BPI input data into a BPI workstep SHOULD be sourced from multiple endpoints.
[R320] External non-authoritative BPI input data into a BPI workstep MUST be validated by one or more authoritative entities. 
Authoritative entities in the context of this document are entities that have been delegated authority by the participants of a BPI workstep to validate an external non-authoritative source of input data into a BPI workstep.
[R321] BPI participants MUST agree upon a standard validation method for external non-authoritative data input to a BPI workstep.
[R322] A BPI workstep participant MUST be able to validate that the validation criteria of an external non-authoritative data input to the BPI workstep has been met. 
Appropriate data validation methods vary on a case-by-case basis depending upon the data types, sources and formats. As such, it is up to the BPI participants to agree upon the optimal validation method for their implementation. This includes design decisions such as what threshold of unresponsive oracles leads to a rejected input, how to aggregate the oracle responses and remove outliers, signing data to ensure provenance, implementing cryptographic mechanisms such as threshold signatures/secret sharing and TEEs to obfuscate data from the oracle providers.

8.3.2 External Non-authoritative BPI Input Data Variance
External non-authoritative BPI input data can be subject to variations from lack of time synchronicity, fluctuations in precision or reporting error. Party A may read the temperature of a shipment as 77.1F while party B reads it as 77.3F. Small variance in timing can also produce mismatched BPI data inputs. These variations may lead to failed proof verification if proof inputs are not identical between prover and verifier. In order for proofs to be deterministic, the inputs to a BPI workstep must also uphold determinism by removing these variances through a chosen variance removal algorithm across the disparate data points such as mean, median, etc which aggregates the data into a single golden truth. As an extension of data validation, it's up to the BPI participants to agree upon their algorithmic approach to removing variance and outlier data. This agreed-upon method should have a clearly defined standard with all oracles involved adhering to the same data format. In the case where there are multiple data endpoints, there's both the variance for each oracle's internal data set and the variance between their aggregated answers to consider.

**Review by Therecanbeonlyone1969 — APPROVED** [review]

**Comment by Therecanbeonlyone1969** [comment]
@gmondok ... please, resolve changes with Core, and make sure that you are associated with the Chainlink IPR agreement @OASIS-OP-Admin  ... please associate @gmondok with the chainlink IPR agreement. Thank you!

**Comment by Consianimis** [comment]
@Therecanbeonlyone1969, @gmondok  - We will take care of resolving changes with CORE.

**Pull request closed without merging**
